### ISSUE TITLE
react-native

### ISSUE THREAD

**Issue by webmobiles** [tkrotoff/react-form-with-constraints#4]
html5 can be integrated to react-native?

i'm using redux-form  but don't work well like angular4  reactive-form, i'm looking for to have control about states on the fields

![angular4-control-state-transitions-anim](https://user-images.githubusercontent.com/21120559/31582732-dde1455c-b18b-11e7-92d3-4b0f14551db9.gif)

**Comment by tkrotoff** [comment]
Not sure what you mean.
HTML5 attributes (`required`, `pattern`...) cannot possibly work with React Native.
Can react-form-with-constraints work with React Native? Not currently. Might be possible to make `FieldFeedbacks` and `FieldFeedback` work given some modifications.

**Comment by tkrotoff** [comment]
@webmobiles I've added React Native support with version 0.7.0 and npm package react-form-with-constraints-native. Check the example: https://github.com/tkrotoff/react-form-with-constraints/tree/v0.7.0/examples/ReactNative
