### ISSUE TITLE
Issues with warning and info FieldFeedback type  

### ISSUE THREAD

**Issue by phong-steph** [tkrotoff/react-form-with-constraints#49]
In the example below, I have 3 FieldFeedback of different type (error, warning and info). 
As you can see, except for error, the inputs for warning and info have respectively these classes `'is-warning is-valid'` and `'is-info is-valid'` (so `'is-valid'` style is applied) while error input class has not `is-valid` class.

Is it a wanted behavior? 
Thanks ;)

![image](https://user-images.githubusercontent.com/10865520/68312961-1d112e80-00b4-11ea-96df-82ace9ef5783.png)

Codesandbox => https://codesandbox.io/s/react-form-with-constraint-bootstrap4-mujvc

**Comment by phong-steph** [comment]
I found a quiick fix in this [file](https://github.com/tkrotoff/react-form-with-constraints/blob/v0.14.0/packages/react-form-with-constraints/src/Input.tsx#L92):
Instead of pushing all differentes states for one input, push only one state for one input (ordered by priority).

from:
``` 
        if (field.hasErrors()) states.push('hasErrors');
        if (field.hasWarnings()) states.push('hasWarnings');
        if (field.hasInfos()) states.push('hasInfos');
        if (field.isValid()) states.push('isValid');
```
to:
```
        if (field.hasErrors()) states.push('hasErrors');
        else if (field.hasWarnings()) states.push('hasWarnings');
        else if (field.hasInfos()) states.push('hasInfos');
        else if (field.isValid()) states.push('isValid');
```

result:
![image](https://user-images.githubusercontent.com/10865520/68407447-e1459a00-0183-11ea-804c-e78dc720ae3c.png)

**Comment by tkrotoff** [comment]
Sorry for the delay, I'm AFK until mid december.

An input can have warnings and/or infos and still be valid. Ce n'est donc pas exclusif.
hasErrors state is the only invalid state, others (info, warning) are considered valid. You can override the CSS if you want a different styling.

Here the related Sass code source: https://github.com/tkrotoff/react-form-with-constraints/blob/v0.14.0/packages/react-form-with-constraints-bootstrap4/scss/bootstrap.scss#L143-L150

Je pense que dans ton exemple le "wording" des feedbacks n'est pas le bon et devrait être :
- hasErrors state/invalid class : "Cette information *est* incorrect"
- hasWarnings state/warning class : "Vérifiez cette information, elle *semble/est peut être* incorrect"
- hasInfos state/info class : "pour information blabla"

**Comment by phong-steph** [comment]
Overriding CSS will be the easiest solution thx!
