### ISSUE TITLE
Async await on emitEvent

### ISSUE THREAD

**Issue by phong-steph** [tkrotoff/react-form-with-constraints#51]
Hello,

I got asynchronous problems on updating input styling after validated my form's inputs with validateFields().
Indeed the status of inputs are validated but not the styling so I need to use a timer to force the input  to update. 
The issue seems to come from 

> this.emitFieldWillValidateEvent()

 and 

> this.emitFieldDidValidateEvent() 

https://github.com/tkrotoff/react-form-with-constraints/blob/v0.13.0/packages/react-form-with-constraints/src/FormWithConstraints.tsx

**Comment by tkrotoff** [comment]
See 8939cf2aa246f8de218ab96101e72873b2203209, fixed in v0.15.0
