### ISSUE TITLE
Form with constraints components dont work with react 18

### ISSUE THREAD

**Issue by enqbator** [tkrotoff/react-form-with-constraints#58]
When building with webpack / typescript / @babel/react react-form-with-constrains components prevent my project from building after updating to react 18.

Build functions again after downgrading back to react 17.

"FieldFeedbacks cannot be used as a jsx component"

"Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FieldFeedbacks> & Pick<Readonly<FieldFeedbacksProps>, never> & Partial<...>'."

**Comment by enqbator** [comment]
To clarify, it looks to be caused breaking changes in the react typescript bindings.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

**Comment by enqbator** [comment]
@andrec93p Thank you for that. I was looking at having to use something else for validation, which is a shame. Every other validation package seems to be way more complicated than they need to be and just plain invasive in the way they affect how you have to make the form/access the values.

It would have meant reworking all the markup and even loading / saving logic in all of my apps forms.

Thanks again.

**Comment by tkrotoff** [comment]
Big PR that fixes this (among other things): https://github.com/tkrotoff/react-form-with-constraints/pull/59

**Comment by tkrotoff** [comment]
Fix published in v0.19.0
